### ISSUE TITLE
Feature/enhancement list

### ISSUE THREAD

**Issue by sclayton33** [PistilliLab/CLAMSwrangler#5]
Features/enhancements that need to be added:
- [Seems fine now] Improve font style, hard to read.
- ~Add a dropdown selector for bin hours option~
- TESTS OH BOY
- [DONE] convert filepaths to lower if the filedialog does not do that already
- [DONE, mostly] Add error handling where logical to prevent hangs, crashing

Features/enhancements to consider:
- [DONE] Add checkboxes for light/dark only
- [DONE] Add more dialog output for user on state of processes (each file processed)
- [DONE] Add more details to each combined filename (bin size)
- Add user input check for the number of hours to keep, if beyond the maximum number of hours remaining after trimming return error message
- Add user input check for bin hours, if nothing input then us a default. If not a factor of 12, then return error to console.
- Add data format check to ensure that the .csv being input matching the existing output format in case of future changes to it.
- Add outlier checking
- Add quick visualization of data for each variable, will require extensive work though

**Comment by admizener** [comment]
- Adjust trimming procedure so that multiple cohorts will always have a synchronized light/dark cycle for analysis
- Adjust trimming procedure so that cumulative variables are zeroed at the start of the analysis period

**Comment by sclayton33** [comment]
> * Adjust trimming procedure so that multiple cohorts will always have a synchronized light/dark cycle for analysis
> * Adjust trimming procedure so that cumulative variables are zeroed at the start of the analysis period

For reference, these are fixed in commit [b1a1d32fcd37ae90ec18454cf045a01ca71963a2](https://github.com/PistilliLab/CLAMSwrangler/commit/b1a1d32fcd37ae90ec18454cf045a01ca71963a2)

**Comment by admizener** [comment]
Features/Enhancements to add:
-Add staistical analysis
-Add plotting functionality (e.g., bar plots, regression plots)
-Add web interface
-Add checks for abnormal data point
-Add checks for appropriate correlation between metabolic variables and mass
-Unnormalize raw clams data using subject mass

**Comment by sclayton33** [comment]
Features to add have been moved to [v2.0 project board](https://github.com/orgs/PistilliLab/projects/3/views/1).
